@extends('layouts.app')

@section('content')
@php($visibleLines = $movement->lines->reject(fn ($line) => ($line->item_snapshot['item_type'] ?? null) === App\Models\InventoryItem::TYPE_SIM_CARD))
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="page-title"><span class="text-mono">{{ $movement->movement_number }}</span></div><div class="text-muted">{{ App\Models\InventoryMovement::typeOptions()[$movement->movement_type] ?? $movement->movement_type }} recorded {{ $movement->occurred_at->format('m/d/Y H:i') }}</div></div><div class="btn-group"><a class="btn btn-outline-secondary btn-sm" href="{{ route('movements.index') }}">History</a><form method="POST" action="{{ route('movements.documents.store', $movement) }}">@csrf<button class="btn btn-primary btn-sm">Generate DOCX</button></form></div></div>
<div class="row g-3">
    <div class="col-lg-4"><div class="card"><div class="card-header fw-semibold">Summary</div><div class="card-body small"><dl class="row mb-0"><dt class="col-4">User</dt><dd class="col-8">{{ $movement->user?->name }}</dd><dt class="col-4">Client</dt><dd class="col-8">{{ $movement->client?->name ?? 'Internal' }}</dd><dt class="col-4">From</dt><dd class="col-8">{{ $movement->fromLocation?->label() ?? 'N/A' }}</dd><dt class="col-4">To</dt><dd class="col-8">{{ $movement->toLocation?->label() ?? 'N/A' }}</dd><dt class="col-4">Notes</dt><dd class="col-8">{{ $movement->notes ?: 'None' }}</dd></dl></div></div><div class="card mt-3"><div class="card-header fw-semibold">Documents</div><div class="list-group list-group-flush">@forelse($movement->documents as $doc)<a class="list-group-item list-group-item-action small" href="{{ route('generated-documents.download', $doc) }}">{{ $doc->original_filename }}<div class="text-muted">Generated {{ $doc->generated_at->format('m/d/Y H:i') }} by {{ $doc->user?->name }}</div></a>@empty<div class="list-group-item text-muted small">No documents generated.</div>@endforelse</div></div></div>
    <div class="col-lg-8"><div class="card"><div class="card-header fw-semibold">Movement Lines</div><div class="list-group list-group-flush">@forelse($visibleLines as $line)@php($snap=$line->item_snapshot)<div class="list-group-item"><div class="row g-2 small"><div class="col-md-1"><div class="text-muted">Seq</div>{{ $line->sequence }}</div><div class="col-md-3"><div class="text-muted">Asset</div><a class="text-mono" href="{{ route('inventory-items.show', $line->inventoryItem) }}">{{ $snap['asset_tag'] ?? $line->inventoryItem?->asset_tag }}</a></div><div class="col-md-2"><div class="text-muted">Type</div>{{ str($snap['item_type'] ?? '')->headline() }}</div><div class="col-md-3"><div class="text-muted">Previous</div>{{ $line->previousLocation?->label() ?? 'N/A' }}<div class="text-muted">{{ $line->previous_status }}</div></div><div class="col-md-3"><div class="text-muted">New</div>{{ $line->newLocation?->label() ?? 'N/A' }}<div class="text-muted">{{ $line->new_status }}</div></div></div><div class="bg-light rounded p-2 mt-2 small"><div class="fw-semibold mb-1">Captured Identifiers</div>@if($snap['phone'] ?? null)@php($sim = $snap['phone']['assigned_sim'] ?? null)@if($snap['phone']['imei'] ?? null)<div>IMEI <span class="text-mono text-break">{{ $snap['phone']['imei'] }}</span></div>@endif @if($sim)<div>SIM <span class="text-mono text-break">{{ $sim['iccid'] ?? '' }}</span></div><div>Phone # <span class="text-mono">{{ $sim['associated_phone_number'] ?? $sim['phone_number'] ?? 'N/A' }}</span></div><div>Activation {{ $sim['activation_status'] ?? 'N/A' }}</div>@endif @elseif($snap['modem'] ?? null)@php($sim = $snap['modem']['assigned_sim'] ?? null)@if($snap['modem']['imei'] ?? null)<div>IMEI <span class="text-mono text-break">{{ $snap['modem']['imei'] }}</span></div>@endif @if($sim)<div>SIM <span class="text-mono text-break">{{ $sim['iccid'] ?? '' }}</span></div><div>Phone # <span class="text-mono">{{ $sim['associated_phone_number'] ?? $sim['phone_number'] ?? 'N/A' }}</span></div><div>Activation {{ $sim['activation_status'] ?? 'N/A' }}</div>@endif @else<span class="text-mono text-break">{{ $snap['serial_number'] ?? '' }}</span>@endif</div></div>@empty<div class="list-group-item text-muted small">No non-SIM movement lines recorded.</div>@endforelse</div></div></div>
</div>
@endsection
