@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="page-title"><span class="text-mono">{{ $movement->movement_number }}</span></div><div class="text-muted">{{ App\Models\InventoryMovement::typeOptions()[$movement->movement_type] ?? $movement->movement_type }} recorded {{ $movement->occurred_at->format('m/d/Y H:i') }}</div></div><div class="btn-group"><a class="btn btn-outline-secondary btn-sm" href="{{ route('movements.index') }}">History</a><form method="POST" action="{{ route('movements.documents.store', $movement) }}">@csrf<button class="btn btn-primary btn-sm">Generate DOCX</button></form></div></div>
<div class="row g-3">
    <div class="col-lg-4"><div class="card"><div class="card-header fw-semibold">Summary</div><div class="card-body small"><dl class="row mb-0"><dt class="col-4">User</dt><dd class="col-8">{{ $movement->user?->name }}</dd><dt class="col-4">Client</dt><dd class="col-8">{{ $movement->client?->name ?? 'Internal' }}</dd><dt class="col-4">From</dt><dd class="col-8">{{ $movement->fromLocation?->label() ?? 'N/A' }}</dd><dt class="col-4">To</dt><dd class="col-8">{{ $movement->toLocation?->label() ?? 'N/A' }}</dd><dt class="col-4">Notes</dt><dd class="col-8">{{ $movement->notes ?: 'None' }}</dd></dl></div></div><div class="card mt-3"><div class="card-header fw-semibold">Documents</div><div class="list-group list-group-flush">@forelse($movement->documents as $doc)<a class="list-group-item list-group-item-action small" href="{{ route('generated-documents.download', $doc) }}">{{ $doc->original_filename }}<div class="text-muted">Generated {{ $doc->generated_at->format('m/d/Y H:i') }} by {{ $doc->user?->name }}</div></a>@empty<div class="list-group-item text-muted small">No documents generated.</div>@endforelse</div></div></div>
    <div class="col-lg-8"><div class="card"><div class="card-header fw-semibold">Movement Lines</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Seq</th><th>Asset</th><th>Type</th><th>Previous</th><th>New</th><th>Captured Identifiers</th></tr></thead><tbody>@foreach($movement->lines as $line)@php($snap=$line->item_snapshot)<tr><td>{{ $line->sequence }}</td><td><a class="text-mono" href="{{ route('inventory-items.show', $line->inventoryItem) }}">{{ $snap['asset_tag'] ?? $line->inventoryItem?->asset_tag }}</a></td><td>{{ str($snap['item_type'] ?? '')->headline() }}</td><td>{{ $line->previousLocation?->label() ?? 'N/A' }}<div class="small text-muted">{{ $line->previous_status }}</div></td><td>{{ $line->newLocation?->label() ?? 'N/A' }}<div class="small text-muted">{{ $line->new_status }}</div></td><td class="small text-mono">@if($snap['phone'] ?? null)Phone {{ $snap['phone']['phone_number'] ?? '' }} IMEI {{ $snap['phone']['imei'] ?? '' }} SIM {{ $snap['phone']['assigned_sim']['iccid'] ?? '' }}@elseif($snap['sim_card'] ?? null)ICCID {{ $snap['sim_card']['iccid'] ?? '' }} IMSI {{ $snap['sim_card']['imsi'] ?? '' }}@elseif($snap['modem'] ?? null)IMEI {{ $snap['modem']['imei'] ?? '' }} SIM {{ $snap['modem']['assigned_sim']['iccid'] ?? '' }}@else{{ $snap['serial_number'] ?? '' }}@endif</td></tr>@endforeach</tbody></table></div></div></div>
</div>
@endsection
